### ISSUE TITLE
Disable read_max_on_auth_fail by default

### ISSUE THREAD

**Issue by propertone** [deshaw/wsgi-kerberos#27]
So, I just spent a while troubleshooting a production issue where uploading a 20MB file was failing with a connection reset message.

The problem is that unless you have debug logging enabled (which is usually not the case in production), this is a very difficult to troubleshoot issue. I think the very real possibility of this causing difficult to troubleshoot production issues is just not worth the hypothetical DoS protection, especially since most production setups have a front-end server where you configure the max body size anyway. Even if we change the log level to error, it's not guaranteed to work correctly or may output spurious errors.

Thought, @jab?

**Comment by propertone** [comment]
Btw, the "naively written client" in this case is the python requests library. Sending the full request body on an unauthenticated request is the default behavior.

**Comment by jab** [comment]
That default behavior is indeed naive, and it sounds like this helped you uncover it (though I’m sorry to hear it was hard for you to debug). Wouldn’t you much prefer to be avoiding these large, wasteful, destined-for-401 uploads in the first place, e.g. by passing `force_preemptive=True` to `requests_kerberos`?

**Comment by propertone** [comment]
Well, I figured it out only because I remembered about the recent wsgi_kerberos change. Yes, using `force_preemptive=True` would be a good idea for my use case.

But this issue is not about me - it's about all other potential users of the library. And this behavior introduces corner cases that are unlikely to be caught during development and would be very difficult to debug in production. If you're using wsgi_kerberos, chance is that it's for an internal company application, so even the idea of having to worry about DoS protection is questionable.

We can still leave this option, but I suggest changing the default to be no limit.

**Comment by jab** [comment]
DoS can happen by accident, even when everyone is within the same company. I don't think having a default that protects against it is questionable, I think it's helpful. I think a default that allows the server to sit there forever consuming the body of a client that is streaming an upload of an infinitely large request body (whether maliciously or just accidentally) and that's never willing to give up and send the 401 is the more harmful default.

In this case, once clients within the company are corrected to use `force_preemptive=True` (uncovered thanks to this better default), they'll observe higher success rates for their requests and lower latencies since they won't waste time with an expensive initial round-trip that's destined to fail. I think this is a healthy change to keep for our 0.2 -> 1.0 (more production-ready) version jump, but we should make the following improvement to the changelog:

**WARNING**: If your clients are using `requests/requests_kerberos` with its default settings (or any other library that by default uploads arbitrarily large initial requests without authentication (that are therefore destined to fail with a 401) and that nonetheless still expect the server to consume the entire request body), you can work around this client deficiency by ensuring clients are configured with the `force_preemptive=True` option. This helps them avoid seeing errors on large unauthenticated uploads (and reduces the latencies they see on all requests). You can also set a higher `read_max_on_auth_fail` to work around this in WSGI-Kerberos, to trade off server resources for more accommodation of naive clients.

**Comment by propertone** [comment]
I disagree. We introduced a breaking change to a library that provides little value.

@mkomitee @mlucool - thoughts?

**Comment by mkomitee** [comment]
Looks like it took a very short amount of time for someone using a very common library to encounter an issue in production because of the change. 

I think we should probably disable the new behavior by default, and instead set a threshold and issue warnings about potential DoS attempts (intentional or otherwise) when the relevant code ends up consuming more than a “reasonable” amount of data for the purpose of discarding and issuing a 401. Maybe the warning should include a link to a recommendation to opt-in to the behavior we presently have as default and/or how to configure it in common proxies like nginx / apache.

**Comment by jab** [comment]
Rather than reverting WSGI-Kerberos to being willing to read an infinite amount of data, why not bump the default `read_max_on_auth_fail` from 10 MB to 100 MB, or even something higher? Having *some* limit seems like much safer default behavior for a server than allowing it to read and discard data from a request forever.

**Comment by mkomitee** [comment]
Just throwing out an idea, maybe we can make it time based rather than size based?

**Comment by jab** [comment]
Incorporating a time-based limit definitely has some advantages (e.g. defending against [slowloris-like clients](https://en.wikipedia.org/wiki/Slowloris_(computer_security)), which you otherwise need e.g. NGINX for). Though I think we'd want to keep a size-based limit too, not replace it with a time-based limit. If we had to choose one of the two, having just a size-based limit means there's a single limit we have to maintain that composes with the existing Content-Length-based limit that we'd always want to continue to check.

One thing I'd be curious about is whether removing the short-circuit code we have in the following lines would have made this easier for @propertone to debug or would have only masked the underlying problem with the client further:
https://github.com/deshaw/wsgi-kerberos/blob/1104e6928e8cf3fa67e6d0f177753cae236f72e0/wsgi_kerberos.py#L64-L67

**Comment by propertone** [comment]
Reading up to read_max bytes does not help prevent connection reset errors with python requests.
Another thing - if the main concern is about blowing up memory usage, then this can be solved by reading the data in chunks. Otherwise, just setting the limit inside wsgi_kerberos doesn't really help prevent DoS since normal authenticated requests can still blow past the limit. And if that's the concern, then the limit should be set in the proxy server, which will apply to both authenticated and unauthenticated requests.

**Comment by jab** [comment]
> Another thing - if the main concern is about blowing up memory usage, then this can be solved by reading the data in chunks.

The main concern is not just blowing up memory usage, it's wasting resources in general (could be time, bandwidth, CPU, open file descriptors on the host, all kinds of things could be limiting factors for the various applications and environments where WSGI-Kerberos should work well). Note, we changed the code in my original PR which was reading the data in chunks when we decided on the 10 MB default maximum, which is small enough that we thought we could get away without reading in chunks. But I agree we should actually be reading no more than *_CHUNK_MAX* at a time given that users can choose a larger *read_max_on_auth_fail* than our default. I'm happy to submit a PR for that along with any changes we want to make based on this discussion.

> just setting the limit inside wsgi_kerberos doesn't really help prevent DoS since normal authenticated requests can still blow past the limit

In the case that WSGI-Kerberos successfully authenticates a request, it passes the request through to the WSGI application without reading or buffering any of the request body. The WSGI application is then responsible for reading however much of the request body without buffering arbitrarily large uploads entirely into memory, which WSGI frameworks like Flask etc. explicitly help with. Note that in this case (successful authentication and pass through to the WSGI application), the application itself may not read the entire request body, in which case, naively-written clients that don't handle servers that aren't always reading the entire request body will still blow up, even when they authenticate successfully. (It's really too bad requests is in this category, but good to see that [next-generation Python http clients like Hip are trying to be better about this](https://github.com/python-trio/hip/issues/49).)

**Comment by jab** [comment]
I realized there's another way we could mitigate requests' + requests_kerberos's (and similarly naive clients') bad behavior here, that doesn't necessarily require a change on the client side like setting `force_preemptive=True` (or equivalent), and that doesn't require compromising on WSGI-Kerberos's security:

WSGI-Kerberos could set a credential that persists across requests such as a session cookie based on the client's Kerberos credential. Then, after a client's initial request, all subsequent requests that it makes in the session will send back the Cookie header that WSGI-Kerberos set after the initial successful authentication. (This is a [commonly implemented optimization](https://github.com/twosigma/waiter) on top of SPNEGO that is worth doing in its own right, because it reduces server load and client latencies by saving clients from needless extra 401 roundtrips.)

```python
# existing client code, not using preemptive auth:
with requests.Session(auth=KerberosAuth()) as sess:
    # Initial authentication requires SPNEGO (at least two roundtrips)
    resp = sess.get(...)
    # But now the response has a session cookie;
    # subsequent requests in this session incur no additional 401s:
    sess.get(...)
    # Including large uploads:
    sess.post(...)
    # These all now succeed on the first try.
    # No more needlessly-destined-to-401 requests, and no need to update this client code:
    sess.put(...)
    ...
```

**Comment by propertone** [comment]
The main issue for me is that we introduced a breaking change for what I consider (although you may disagree) to be questionable value. Increasing the limit will just make it less likely that the limit will be hit, but it's still a breaking change. The idea of limiting request bodies is certainly not a standard behavior in web servers - for example apache, flask, and lighttpd don't set any limits on the request body size by default (nginx does). Even in golang, ParseMultipartForm, take a required max size parameter.

**Comment by propertone** [comment]
Any client-side workarounds are not relevant since the application may not have control over the client-side code.

**Comment by jab** [comment]
The point of my previous comment is that if WSGI-Kerberos used a session cookie, it would allow client code that is already using a request.Session as in my example to take advantage of request.Session’s built-in-by-default cookie support, with no changes to the client code required.

**Comment by jab** [comment]
Well, you could argue any secure-by-default protections aren’t valuable while you’re not having the problem, until you are, and you wish you’d had them in the first place. In general it’s better to set users up for more security by default rather than requiring they opt into it. I know the DoS protection caused an issue for you, and not having it didn’t, but that doesn’t mean that not having it by default wouldn’t cause a serious production issue for other users (or even your own use sometime in the future). In general servers should not knowingly leave DoS vectors open by default to accommodate bad clients, even popular ones.

I can speak for Flask (as a Pallets maintainer myself). The MAX_CONTENT_LENGTH is not set by default but Flask also never reads the request body unless the application explicitly asks for it. The WSGI-Kerberos default behavior you propose is to read the entire request body on 401 without the application explicitly asking for it.
Also, when there is no Content-Length header, Flask’s default behavior is to not read any of the request body on-demand (when request.data is accessed) as a security precaution. That’s very different from what you’re proposing here.

**Comment by jab** [comment]
@propertone, I've been testing the changes from #15 in the v1.0.0 release in more environments, and just noticed an issue that could cause WSGI-Kerberos to hang (depending on the WSGI server) for requests with no Content-Length header. I've submitted #28 with a fix for that issue, as well as reading the request in chunks as mentioned in this issue.

**Comment by jab** [comment]
Remembered https://werkzeug.palletsprojects.com/en/1.0.x/request_data/ has some really good, relevant advice here.

**Comment by propertone** [comment]
Ok, how about:
* Increase the default limit to 200MB
* Log a useful error/warning message when `content_length > read_max`

**Comment by twosigmajab** [comment]
Sounds good to me. Done in #28.
